"""
Seed the Research Agent database with a large set of AI tools.
Run from the backend directory with the virtualenv active:
    python3 seed_tools.py
"""

import json
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from database import SessionLocal, engine, Base
from models import Tool

Base.metadata.create_all(bind=engine)

TOOLS = [
    # ── Frontier LLM chat ─────────────────────────────────────────────────
    {
        "name": "ChatGPT",
        "url": "https://chat.openai.com",
        "description": "OpenAI's conversational AI assistant",
        "signal_summary": "ChatGPT is OpenAI's flagship conversational AI assistant, supporting text, images, files, and web browsing. It powers everything from writing and coding to research and analysis across millions of users. Available as a free tier and ChatGPT Plus/Team/Enterprise subscriptions.",
        "use_cases": ["productivity", "writing-assistance", "code-generation", "research", "data-analysis"],
        "price_tier": "freemium",
        "target_audience": "everyone — students, professionals, developers, creatives",
        "click_count": 980,
    },
    {
        "name": "Claude",
        "url": "https://claude.ai",
        "description": "Anthropic's AI assistant — safe, capable, and honest",
        "signal_summary": "Claude is Anthropic's AI assistant known for its long context window, nuanced reasoning, and strong writing quality. It excels at document analysis, coding, and thoughtful conversation with a safety-first design. Available via claude.ai and the Anthropic API with Pro/Team/Enterprise tiers.",
        "use_cases": ["writing-assistance", "research", "code-generation", "data-analysis", "productivity"],
        "price_tier": "freemium",
        "target_audience": "developers, researchers, writers, enterprise teams",
        "click_count": 870,
    },
    {
        "name": "Gemini",
        "url": "https://gemini.google.com",
        "description": "Google's multimodal AI assistant",
        "signal_summary": "Gemini is Google's multimodal AI assistant integrated across Google Workspace, Search, and Android. It handles text, images, audio, video, and code with deep integration into Gmail, Docs, and Drive. Available free with Gemini Advanced on Google One subscription.",
        "use_cases": ["productivity", "research", "writing-assistance", "code-generation", "data-analysis"],
        "price_tier": "freemium",
        "target_audience": "Google Workspace users, students, developers",
        "click_count": 820,
    },
    {
        "name": "Grok",
        "url": "https://grok.com",
        "description": "xAI's real-time AI assistant with X integration",
        "signal_summary": "Grok is xAI's conversational AI with real-time access to X (Twitter) posts and web search, making it uniquely suited for current events and trending topics. It supports image understanding and code generation. Available to X Premium subscribers and via xAI API.",
        "use_cases": ["research", "writing-assistance", "code-generation", "productivity"],
        "price_tier": "freemium",
        "target_audience": "X platform users, journalists, researchers",
        "click_count": 610,
    },
    {
        "name": "Perplexity AI",
        "url": "https://perplexity.ai",
        "description": "AI-powered answer engine with cited sources",
        "signal_summary": "Perplexity is an AI-powered answer engine that combines web search with LLM synthesis to give cited, up-to-date responses. It excels at research queries where source attribution matters. Offers a free tier and Perplexity Pro with access to GPT-4o, Claude, and more.",
        "use_cases": ["research", "data-analysis", "productivity"],
        "price_tier": "freemium",
        "target_audience": "researchers, students, knowledge workers",
        "click_count": 540,
    },
    {
        "name": "Qwen",
        "url": "https://chat.qwenlm.ai",
        "description": "Alibaba's open-source LLM and assistant",
        "signal_summary": "Qwen is Alibaba's family of open-source large language models available via web chat and API. It supports long-context reasoning, code generation, and multilingual tasks with strong performance in Chinese and English. Models range from 0.5B to 72B+ parameters and are freely available on Hugging Face.",
        "use_cases": ["code-generation", "writing-assistance", "research", "productivity"],
        "price_tier": "free",
        "target_audience": "developers, researchers, multilingual users",
        "click_count": 290,
    },
    {
        "name": "Manus",
        "url": "https://manus.im",
        "description": "Autonomous AI agent that completes complex tasks end-to-end",
        "signal_summary": "Manus is a general-purpose autonomous AI agent that can browse the web, write and execute code, manage files, and complete multi-step research or business tasks without human intervention. It represents a new category of agentic AI beyond chat interfaces. Currently invite-only with plans for broader access.",
        "use_cases": ["automation", "research", "productivity", "code-generation", "data-analysis"],
        "price_tier": "paid",
        "target_audience": "power users, developers, business analysts",
        "click_count": 480,
    },
    {
        "name": "DeepSeek",
        "url": "https://chat.deepseek.com",
        "description": "High-performance open-source reasoning LLM from China",
        "signal_summary": "DeepSeek offers state-of-the-art open-source language models including DeepSeek-R1, a reasoning model competitive with o1 at a fraction of the cost. Its models are freely available on Hugging Face and via API. Particularly strong at math, coding, and multi-step reasoning tasks.",
        "use_cases": ["code-generation", "research", "data-analysis", "writing-assistance"],
        "price_tier": "free",
        "target_audience": "developers, researchers, AI enthusiasts",
        "click_count": 430,
    },
    {
        "name": "Mistral",
        "url": "https://chat.mistral.ai",
        "description": "European open-weight LLM platform — fast and efficient",
        "signal_summary": "Mistral AI offers a family of efficient open-weight models including Mistral Large, Mixtral, and Codestral for code generation. Known for high performance relative to model size and transparent European AI development. Free tier via Le Chat and API access for developers.",
        "use_cases": ["code-generation", "writing-assistance", "research", "productivity"],
        "price_tier": "freemium",
        "target_audience": "developers, European enterprises, AI researchers",
        "click_count": 310,
    },
    {
        "name": "Meta AI",
        "url": "https://www.meta.ai",
        "description": "Meta's AI assistant powered by Llama, built into Facebook and WhatsApp",
        "signal_summary": "Meta AI is Meta's conversational assistant powered by Llama 3, integrated into Facebook, Instagram, WhatsApp, and Messenger. It can answer questions, generate images, and assist with tasks across Meta's social platforms. Free to use with a Meta account.",
        "use_cases": ["productivity", "writing-assistance", "image-generation", "research"],
        "price_tier": "free",
        "target_audience": "social media users, everyday consumers",
        "click_count": 360,
    },
    {
        "name": "Antigravity",
        "url": "https://antigravity.ai",
        "description": "AI-powered productivity and knowledge assistant",
        "signal_summary": "Antigravity is an AI productivity tool focused on knowledge synthesis and intelligent task management. It helps users connect ideas, summarise information, and accelerate decision-making workflows. Designed for teams and individuals who work with large volumes of information.",
        "use_cases": ["productivity", "research", "writing-assistance"],
        "price_tier": "freemium",
        "target_audience": "knowledge workers, teams, researchers",
        "click_count": 120,
    },
    # ── Code editors & dev tools ──────────────────────────────────────────
    {
        "name": "Cursor",
        "url": "https://cursor.com",
        "description": "AI-first code editor built on VS Code",
        "signal_summary": "Cursor is an AI-first code editor forked from VS Code that integrates LLM assistance directly into the editing workflow. It offers inline generation, multi-file context awareness, and natural language refactoring with models including GPT-4o and Claude. Freemium with a Pro tier for heavy usage.",
        "use_cases": ["code-generation", "productivity", "writing-assistance"],
        "price_tier": "freemium",
        "target_audience": "software developers",
        "click_count": 760,
    },
    {
        "name": "VS Code",
        "url": "https://code.visualstudio.com",
        "description": "Microsoft's open-source code editor with GitHub Copilot integration",
        "signal_summary": "VS Code is Microsoft's free, open-source code editor and the most widely used IDE in the world. With GitHub Copilot and a vast extension marketplace, it supports AI-assisted coding across every major language and framework. Free to use with optional Copilot subscription.",
        "use_cases": ["code-generation", "productivity", "automation"],
        "price_tier": "free",
        "target_audience": "software developers of all levels",
        "click_count": 890,
    },
    {
        "name": "GitHub Copilot",
        "url": "https://github.com/features/copilot",
        "description": "AI pair programmer built into GitHub and VS Code",
        "signal_summary": "GitHub Copilot is an AI pair programmer that suggests whole lines and functions in your editor as you type, powered by OpenAI Codex. It integrates with VS Code, JetBrains, Vim, and GitHub.com for code review. Available as an individual subscription or enterprise plan.",
        "use_cases": ["code-generation", "productivity", "automation"],
        "price_tier": "paid",
        "target_audience": "software developers, DevOps engineers",
        "click_count": 720,
    },
    {
        "name": "Windsurf",
        "url": "https://codeium.com/windsurf",
        "description": "Agentic AI code editor by Codeium",
        "signal_summary": "Windsurf is Codeium's agentic AI code editor that goes beyond autocomplete — it can plan, write, debug, and execute multi-step coding tasks autonomously. It features Cascade, an agentic flow that maintains deep codebase awareness across sessions. Competitive with Cursor on a freemium model.",
        "use_cases": ["code-generation", "productivity", "automation"],
        "price_tier": "freemium",
        "target_audience": "software developers",
        "click_count": 510,
    },
    {
        "name": "Replit",
        "url": "https://replit.com",
        "description": "Browser-based IDE with AI agent for building and deploying apps",
        "signal_summary": "Replit is a cloud-based IDE where you can code, collaborate, and deploy apps instantly from a browser. Its AI agent can build entire applications from a description, making it accessible to non-developers. Supports 50+ languages with free and paid tiers.",
        "use_cases": ["code-generation", "productivity", "education", "automation"],
        "price_tier": "freemium",
        "target_audience": "developers, students, no-code builders",
        "click_count": 470,
    },
    {
        "name": "OpenAI Codex CLI",
        "url": "https://github.com/openai/codex",
        "description": "OpenAI's open-source agentic coding tool for the terminal",
        "signal_summary": "OpenAI Codex CLI is a lightweight open-source coding agent that runs in your terminal. It can read your codebase, write and edit files, run shell commands, and iterate on code autonomously. Powered by the o3 and o4-mini models, it is free to use with an OpenAI API key.",
        "use_cases": ["code-generation", "automation", "productivity"],
        "price_tier": "free",
        "target_audience": "software developers, DevOps engineers",
        "click_count": 390,
    },
    {
        "name": "Gemini CLI",
        "url": "https://github.com/google-gemini/gemini-cli",
        "description": "Google's open-source AI agent for your terminal",
        "signal_summary": "Gemini CLI is Google's open-source AI agent that brings Gemini 2.5 Pro directly to your terminal. It can query and edit code, generate content, and orchestrate complex agentic tasks with 1M token context. Free to use with a Google account via Gemini Code Assist.",
        "use_cases": ["code-generation", "automation", "productivity"],
        "price_tier": "free",
        "target_audience": "developers, engineers, power users",
        "click_count": 340,
    },
    {
        "name": "Bolt.new",
        "url": "https://bolt.new",
        "description": "StackBlitz's AI full-stack app builder in the browser",
        "signal_summary": "Bolt.new is StackBlitz's AI-powered full-stack web development environment that can build, run, and deploy complete applications from natural language prompts. It runs entirely in the browser with a full Node.js environment and no setup required. Freemium with token-based usage.",
        "use_cases": ["code-generation", "productivity", "automation"],
        "price_tier": "freemium",
        "target_audience": "developers, designers, entrepreneurs",
        "click_count": 430,
    },
    {
        "name": "v0 by Vercel",
        "url": "https://v0.dev",
        "description": "Vercel's AI UI component generator",
        "signal_summary": "v0 is Vercel's AI tool that generates React/Tailwind UI components from text descriptions and screenshots. It produces production-ready code that can be copied directly into your project. Free tier available with monthly credits for component generation.",
        "use_cases": ["code-generation", "design", "productivity"],
        "price_tier": "freemium",
        "target_audience": "frontend developers, designers",
        "click_count": 380,
    },
    # ── Notebooks & research ──────────────────────────────────────────────
    {
        "name": "NotebookLM",
        "url": "https://notebooklm.google.com",
        "description": "Google's AI research notebook — chat with your sources",
        "signal_summary": "NotebookLM is Google's AI-powered research assistant that lets you upload documents, PDFs, and web pages and then query them conversationally. Its Audio Overview feature generates podcast-style discussions of your sources. Free to use with a Google account.",
        "use_cases": ["research", "writing-assistance", "productivity", "education"],
        "price_tier": "free",
        "target_audience": "students, researchers, journalists, writers",
        "click_count": 580,
    },
    {
        "name": "Pinokio",
        "url": "https://pinokio.computer",
        "description": "One-click installer for local AI apps and models",
        "signal_summary": "Pinokio is a browser-based platform that lets you install and run any open-source AI application locally with one click — including Stable Diffusion, ComfyUI, Llama, and hundreds of community apps. No coding or terminal knowledge required. Completely free and open-source.",
        "use_cases": ["image-generation", "automation", "productivity", "code-generation"],
        "price_tier": "free",
        "target_audience": "AI enthusiasts, creators, researchers who want local models",
        "click_count": 320,
    },
    {
        "name": "Ollama",
        "url": "https://ollama.com",
        "description": "Run large language models locally on your Mac, Linux, or Windows machine",
        "signal_summary": "Ollama makes it trivially easy to download and run open-source language models (Llama 3, Mistral, Gemma, Phi, DeepSeek, etc.) locally on your machine via a simple CLI. It exposes an OpenAI-compatible API so existing tools and scripts work out of the box. Completely free and open-source.",
        "use_cases": ["productivity", "code-generation", "research", "automation"],
        "price_tier": "free",
        "target_audience": "developers, AI enthusiasts, privacy-conscious users",
        "click_count": 560,
    },
    {
        "name": "OpenRouter",
        "url": "https://openrouter.ai",
        "description": "Unified API for 300+ AI models from every major provider",
        "signal_summary": "OpenRouter provides a single OpenAI-compatible API that routes to 300+ models from Anthropic, OpenAI, Google, Meta, Mistral, and open-source providers. It offers automatic fallbacks, cost comparison, and model benchmarks. Pay-as-you-go with no monthly commitment.",
        "use_cases": ["automation", "code-generation", "productivity", "research"],
        "price_tier": "paid",
        "target_audience": "developers, AI startups, researchers building on top of LLMs",
        "click_count": 490,
    },
    # ── Note-taking & PKM ─────────────────────────────────────────────────
    {
        "name": "Capacities",
        "url": "https://capacities.io",
        "description": "AI-powered object-based personal knowledge management",
        "signal_summary": "Capacities is an AI-powered personal knowledge management tool built around typed objects (notes, books, people, media) rather than flat documents. AI features help auto-tag, summarise, and connect content across your knowledge base. Freemium with a paid plan for AI features.",
        "use_cases": ["productivity", "research", "writing-assistance"],
        "price_tier": "freemium",
        "target_audience": "knowledge workers, researchers, students, writers",
        "click_count": 230,
    },
    {
        "name": "Mem",
        "url": "https://mem.ai",
        "description": "AI-first note-taking that organises itself",
        "signal_summary": "Mem is an AI-first note-taking tool that automatically surfaces relevant notes as you write and build a searchable knowledge graph from your content. Its AI can draft emails, summarise meetings, and answer questions from your personal knowledge base. Subscription-based with a team tier.",
        "use_cases": ["productivity", "writing-assistance", "research"],
        "price_tier": "paid",
        "target_audience": "knowledge workers, executives, researchers",
        "click_count": 210,
    },
    {
        "name": "Reflect",
        "url": "https://reflect.app",
        "description": "AI-powered networked note-taking with daily notes and AI assistant",
        "signal_summary": "Reflect is a fast, networked note-taking app with an integrated AI assistant that can edit, summarise, and generate content within your notes. It uses a bidirectional linking graph and syncs instantly across devices. Subscription-based with a clean, minimal design aesthetic.",
        "use_cases": ["productivity", "writing-assistance", "research"],
        "price_tier": "paid",
        "target_audience": "writers, researchers, professionals",
        "click_count": 180,
    },
    {
        "name": "Notion AI",
        "url": "https://notion.com",
        "description": "AI writing assistant embedded in the Notion workspace",
        "signal_summary": "Notion AI is an integrated writing and summarisation assistant inside the popular Notion workspace. It can draft documents, summarise pages, auto-fill databases, translate content, and answer questions from your workspace data. AI features are an add-on to any Notion plan.",
        "use_cases": ["writing-assistance", "productivity", "content-writing", "automation"],
        "price_tier": "freemium",
        "target_audience": "teams, project managers, knowledge workers",
        "click_count": 640,
    },
    {
        "name": "Obsidian",
        "url": "https://obsidian.md",
        "description": "Local-first Markdown notes with AI plugins and knowledge graph",
        "signal_summary": "Obsidian is a local-first Markdown note-taking app with a powerful plugin ecosystem including AI plugins like Smart Connections and Copilot. Its knowledge graph visualises links between notes. Free for personal use with paid sync and publish features.",
        "use_cases": ["productivity", "research", "writing-assistance"],
        "price_tier": "freemium",
        "target_audience": "researchers, writers, developers, PKM enthusiasts",
        "click_count": 520,
    },
    {
        "name": "Taskade",
        "url": "https://taskade.com",
        "description": "AI-powered project management and team collaboration workspace",
        "signal_summary": "Taskade is an all-in-one AI project management and collaboration tool combining tasks, docs, mind maps, and chat in a single workspace. Its AI agents can run autonomous workflows, generate project templates, and handle research tasks. Freemium with team plans.",
        "use_cases": ["productivity", "automation", "writing-assistance", "research"],
        "price_tier": "freemium",
        "target_audience": "teams, freelancers, project managers",
        "click_count": 260,
    },
    {
        "name": "ClickUp",
        "url": "https://clickup.com",
        "description": "All-in-one project management platform with ClickUp AI",
        "signal_summary": "ClickUp is a comprehensive project management platform with AI features for writing, summarising, and automating tasks across projects, docs, and goals. ClickUp AI can generate action items, write status updates, and draft content. Freemium with paid AI add-on.",
        "use_cases": ["productivity", "automation", "writing-assistance"],
        "price_tier": "freemium",
        "target_audience": "teams, project managers, agencies",
        "click_count": 350,
    },
    # ── Writing & content creation ────────────────────────────────────────
    {
        "name": "Mindsera",
        "url": "https://mindsera.com",
        "description": "AI journal for mental fitness and personal growth",
        "signal_summary": "Mindsera is an AI-powered journaling platform that analyses your entries for cognitive patterns, emotions, and mental models. It provides personalised mentorship inspired by figures like Marcus Aurelius and Feynman. Subscription-based, focused on self-improvement and clarity.",
        "use_cases": ["writing-assistance", "productivity", "education"],
        "price_tier": "paid",
        "target_audience": "entrepreneurs, creatives, self-improvement enthusiasts",
        "click_count": 140,
    },
    {
        "name": "Sudowrite",
        "url": "https://sudowrite.com",
        "description": "AI writing tool built for fiction writers and novelists",
        "signal_summary": "Sudowrite is an AI writing assistant purpose-built for fiction — it can write next scenes, brainstorm plot ideas, describe settings, and rewrite prose in different styles. It uses Claude and GPT-4 under the hood with a writing-focused UX. Subscription-based.",
        "use_cases": ["writing-assistance", "content-writing"],
        "price_tier": "paid",
        "target_audience": "novelists, screenwriters, creative writers",
        "click_count": 160,
    },
    {
        "name": "Lex",
        "url": "https://lex.page",
        "description": "AI-powered word processor with unblocking and feedback features",
        "signal_summary": "Lex is a minimal AI-powered word processor designed for writers who need help getting unstuck. It can continue your text, suggest edits, give feedback, and brainstorm ideas without overwhelming you with features. Subscription-based with a clean Google Docs-like interface.",
        "use_cases": ["writing-assistance", "content-writing"],
        "price_tier": "paid",
        "target_audience": "writers, bloggers, essayists",
        "click_count": 130,
    },
    {
        "name": "Jasper",
        "url": "https://jasper.ai",
        "description": "AI content platform for marketing teams",
        "signal_summary": "Jasper is an enterprise AI content platform used by marketing teams to generate on-brand blog posts, ads, social content, and emails at scale. It supports custom brand voice, team workflows, and integrates with SEO and CMS tools. Subscription-based with team and business plans.",
        "use_cases": ["content-writing", "marketing", "writing-assistance"],
        "price_tier": "paid",
        "target_audience": "marketing teams, content agencies, brand managers",
        "click_count": 280,
    },
    {
        "name": "Copy.ai",
        "url": "https://copy.ai",
        "description": "AI-powered GTM platform for sales and marketing copy",
        "signal_summary": "Copy.ai is an AI content and go-to-market platform that automates sales outreach, marketing copy, and blog content. It includes over 90 templates and workflow automation for B2B teams. Freemium with a paid plan for unlimited credits and team features.",
        "use_cases": ["content-writing", "marketing", "sales", "writing-assistance"],
        "price_tier": "freemium",
        "target_audience": "marketers, sales teams, copywriters",
        "click_count": 240,
    },
    {
        "name": "Gamma",
        "url": "https://gamma.app",
        "description": "AI-generated presentations, documents, and webpages",
        "signal_summary": "Gamma generates beautiful presentations, documents, and webpages from a text prompt or outline in seconds. It handles layout, design, and visual polish automatically, letting you focus on content. Freemium with paid plans for custom branding and export options.",
        "use_cases": ["content-writing", "design", "productivity", "marketing"],
        "price_tier": "freemium",
        "target_audience": "presenters, educators, marketers, business professionals",
        "click_count": 370,
    },
    {
        "name": "Grammarly",
        "url": "https://grammarly.com",
        "description": "AI writing assistant for grammar, clarity, and tone",
        "signal_summary": "Grammarly is an AI-powered writing assistant that checks grammar, spelling, clarity, tone, and style across browsers, Google Docs, and desktop apps. GrammarlyGO adds generative AI for drafting and rewriting. Freemium with a paid Premium tier.",
        "use_cases": ["writing-assistance", "productivity", "content-writing"],
        "price_tier": "freemium",
        "target_audience": "students, professionals, non-native English writers",
        "click_count": 750,
    },
    # ── Image & design ────────────────────────────────────────────────────
    {
        "name": "Midjourney",
        "url": "https://midjourney.com",
        "description": "AI image generation — the highest aesthetic quality available",
        "signal_summary": "Midjourney is a leading AI image generation platform renowned for its distinctive high-quality aesthetic and artistic style. Users generate images via Discord prompts or the web app. Subscription-based with no free tier, starting at $10/month.",
        "use_cases": ["image-generation", "design", "marketing"],
        "price_tier": "paid",
        "target_audience": "designers, artists, marketers, creative professionals",
        "click_count": 680,
    },
    {
        "name": "DALL-E 3",
        "url": "https://openai.com/dall-e-3",
        "description": "OpenAI's text-to-image model integrated in ChatGPT",
        "signal_summary": "DALL-E 3 is OpenAI's text-to-image model known for precise prompt adherence and natural language understanding. It is integrated directly into ChatGPT, allowing conversational image generation and iteration. Available to ChatGPT Plus/Team subscribers and via the Images API.",
        "use_cases": ["image-generation", "design", "content-writing"],
        "price_tier": "freemium",
        "target_audience": "creators, marketers, developers, ChatGPT users",
        "click_count": 460,
    },
    {
        "name": "Adobe Firefly",
        "url": "https://firefly.adobe.com",
        "description": "Adobe's family of generative AI tools for images, text effects, and video",
        "signal_summary": "Adobe Firefly is a family of generative AI models built into Photoshop, Illustrator, and Express for commercial-safe image generation, text effects, and generative fill. Trained on licensed Adobe Stock content. Freemium via Adobe Express with Firefly credits included in Creative Cloud.",
        "use_cases": ["image-generation", "design", "content-writing"],
        "price_tier": "freemium",
        "target_audience": "graphic designers, photographers, creative professionals",
        "click_count": 490,
    },
    {
        "name": "Canva",
        "url": "https://canva.com",
        "description": "Online design platform with Magic AI suite for non-designers",
        "signal_summary": "Canva is the world's most popular online design tool with an extensive Magic AI suite including Magic Write, Magic Design, AI image generation, and background removal. It covers social media graphics, presentations, video, and print. Freemium with Canva Pro for advanced features.",
        "use_cases": ["design", "content-writing", "marketing", "image-generation"],
        "price_tier": "freemium",
        "target_audience": "marketers, small businesses, educators, social media creators",
        "click_count": 830,
    },
    {
        "name": "Figma",
        "url": "https://figma.com",
        "description": "Collaborative UI design tool with AI features",
        "signal_summary": "Figma is the leading browser-based collaborative UI/UX design tool used by product teams worldwide. Recent AI features include auto-layout suggestions, design generation from prompts, and the AI-powered Make Designs plugin. Freemium with paid Professional and Organization plans.",
        "use_cases": ["design", "productivity", "code-generation"],
        "price_tier": "freemium",
        "target_audience": "UI/UX designers, product teams, developers",
        "click_count": 700,
    },
    {
        "name": "Stability AI",
        "url": "https://stability.ai",
        "description": "Open-source Stable Diffusion image and video generation models",
        "signal_summary": "Stability AI is the company behind Stable Diffusion, the world's most widely used open-source image generation model. Its models power thousands of tools and can be run locally, fine-tuned, and used commercially. API access and hosted platform available with free credits.",
        "use_cases": ["image-generation", "design", "video-generation"],
        "price_tier": "freemium",
        "target_audience": "developers, AI artists, researchers, enterprise creators",
        "click_count": 400,
    },
    # ── Video creation ────────────────────────────────────────────────────
    {
        "name": "Runway",
        "url": "https://runwayml.com",
        "description": "AI video generation and editing platform — Gen-3 and beyond",
        "signal_summary": "Runway is a creative AI platform leading in AI-generated video with models including Gen-3 Alpha for text-to-video and video-to-video generation. It also offers professional video editing tools like background removal and object tracking. Freemium with paid plans for longer generations.",
        "use_cases": ["video-generation", "design", "content-writing"],
        "price_tier": "freemium",
        "target_audience": "filmmakers, video editors, VFX artists, content creators",
        "click_count": 500,
    },
    {
        "name": "Kling AI",
        "url": "https://klingai.com",
        "description": "Kuaishou's high-quality AI video generation model",
        "signal_summary": "Kling is Kuaishou's flagship AI video generation model producing high-quality, realistic video clips up to 2 minutes from text and image prompts. It supports camera motion controls and is competitive with Sora for cinematic quality. Freemium with subscription plans.",
        "use_cases": ["video-generation", "content-writing", "design"],
        "price_tier": "freemium",
        "target_audience": "content creators, filmmakers, marketers",
        "click_count": 380,
    },
    {
        "name": "Higgsfield",
        "url": "https://higgsfield.ai",
        "description": "AI video generation with cinematic camera control",
        "signal_summary": "Higgsfield is an AI video generation tool specialising in precise cinematic camera movements and character-consistent video. It allows creators to specify shot types, camera angles, and motion paths for professional-quality outputs. Subscription-based.",
        "use_cases": ["video-generation", "design", "content-writing"],
        "price_tier": "paid",
        "target_audience": "filmmakers, social media creators, advertisers",
        "click_count": 220,
    },
    {
        "name": "CapCut",
        "url": "https://capcut.com",
        "description": "AI-powered video editor popular for short-form content",
        "signal_summary": "CapCut is ByteDance's AI-powered video editing tool popular for creating TikTok and short-form content. It features auto captions, AI avatars, background removal, and smart cut features. Free with a Pro tier for advanced AI features.",
        "use_cases": ["video-generation", "content-writing", "design"],
        "price_tier": "freemium",
        "target_audience": "social media creators, marketers, casual video editors",
        "click_count": 620,
    },
    {
        "name": "Descript",
        "url": "https://descript.com",
        "description": "AI video and podcast editor — edit media by editing text",
        "signal_summary": "Descript lets you edit video and audio by editing a transcript — delete a word in text and the media is cut automatically. AI features include overdub voice cloning, filler word removal, and eye contact correction. Freemium with paid Creator and Business plans.",
        "use_cases": ["video-generation", "audio-generation", "content-writing", "productivity"],
        "price_tier": "freemium",
        "target_audience": "podcasters, YouTubers, journalists, content marketers",
        "click_count": 440,
    },
    {
        "name": "HeyGen",
        "url": "https://heygen.com",
        "description": "AI avatar video generator for marketing and training content",
        "signal_summary": "HeyGen creates professional AI avatar videos where a photorealistic human presents your script in 175+ languages. Used widely for product demos, training videos, and multilingual marketing. Freemium with monthly credit plans.",
        "use_cases": ["video-generation", "marketing", "content-writing"],
        "price_tier": "freemium",
        "target_audience": "marketers, L&D teams, e-commerce businesses",
        "click_count": 310,
    },
    {
        "name": "Sora",
        "url": "https://sora.com",
        "description": "OpenAI's text-to-video model",
        "signal_summary": "Sora is OpenAI's text-to-video model capable of generating high-quality, coherent videos up to 20 seconds from text descriptions. It is integrated into ChatGPT Pro and available via the Sora.com standalone platform. Available to ChatGPT Plus and Pro subscribers.",
        "use_cases": ["video-generation", "content-writing", "design"],
        "price_tier": "paid",
        "target_audience": "filmmakers, advertisers, creative directors",
        "click_count": 550,
    },
    # ── Audio ──────────────────────────────────────────────────────────────
    {
        "name": "ElevenLabs",
        "url": "https://elevenlabs.io",
        "description": "State-of-the-art AI voice synthesis and cloning",
        "signal_summary": "ElevenLabs provides the most realistic AI voice synthesis and voice cloning, supporting 29+ languages with emotional tone control. It is the go-to tool for audiobooks, dubbing, and voice-enabled apps. Freemium with plans scaling by monthly character usage.",
        "use_cases": ["audio-generation", "content-writing", "automation"],
        "price_tier": "freemium",
        "target_audience": "content creators, publishers, developers, accessibility teams",
        "click_count": 590,
    },
    {
        "name": "Suno",
        "url": "https://suno.com",
        "description": "AI music generation from text prompts",
        "signal_summary": "Suno generates complete songs with vocals, instruments, and lyrics from a short text description in under a minute. It supports a wide range of genres and styles and allows commercial use on paid plans. Freemium with daily free credits.",
        "use_cases": ["audio-generation", "content-writing"],
        "price_tier": "freemium",
        "target_audience": "musicians, content creators, game developers, marketers",
        "click_count": 480,
    },
    {
        "name": "Udio",
        "url": "https://udio.com",
        "description": "AI music generation with high-fidelity audio quality",
        "signal_summary": "Udio is an AI music generation platform known for producing high-fidelity, diverse musical outputs including vocals and complex arrangements. It competes with Suno on audio quality and genre range. Freemium with free monthly credits.",
        "use_cases": ["audio-generation", "content-writing"],
        "price_tier": "freemium",
        "target_audience": "musicians, creators, audio producers",
        "click_count": 350,
    },
    {
        "name": "Adobe Podcast",
        "url": "https://podcast.adobe.com",
        "description": "AI audio enhancement and podcast recording in the browser",
        "signal_summary": "Adobe Podcast (Enhance Speech) is a free AI tool that removes background noise and microphone quality issues from audio recordings with one click. It also offers a full browser-based podcast recording and editing suite. Free to use with an Adobe account.",
        "use_cases": ["audio-generation", "content-writing", "productivity"],
        "price_tier": "free",
        "target_audience": "podcasters, journalists, remote workers",
        "click_count": 320,
    },
    # ── Productivity & Google tools ───────────────────────────────────────
    {
        "name": "Google Flow",
        "url": "https://labs.google/flow",
        "description": "Google Labs AI filmmaking tool for Veo video generation",
        "signal_summary": "Google Flow is an AI filmmaking tool from Google Labs that uses Veo 2 to generate cinematic video clips from text and image prompts. It supports scene-by-scene storytelling and camera control features. Available via Google Labs as an early-access experiment.",
        "use_cases": ["video-generation", "design", "content-writing"],
        "price_tier": "free",
        "target_audience": "filmmakers, creative directors, storytellers",
        "click_count": 290,
    },
    {
        "name": "Google Stitch",
        "url": "https://labs.google/stitch",
        "description": "Google Labs AI UI design-to-code tool",
        "signal_summary": "Google Stitch is a Google Labs experiment that generates web UI mockups and React code from text descriptions. It bridges design intent and implementation, allowing rapid prototyping without Figma or manual coding. Available as an early-access experiment.",
        "use_cases": ["design", "code-generation", "productivity"],
        "price_tier": "free",
        "target_audience": "developers, designers, product teams",
        "click_count": 200,
    },
    {
        "name": "Google Mixboard",
        "url": "https://labs.google",
        "description": "Google Labs experimental creative AI mixing and remixing tool",
        "signal_summary": "Google Mixboard is an experimental creative AI tool from Google Labs for remixing images, audio, and visual elements using generative models. It targets creative exploration and rapid ideation. Available as a limited Google Labs experiment.",
        "use_cases": ["image-generation", "audio-generation", "design"],
        "price_tier": "free",
        "target_audience": "creative professionals, designers, experimenters",
        "click_count": 160,
    },
    {
        "name": "Google AI Studio",
        "url": "https://aistudio.google.com",
        "description": "Google's free developer playground for Gemini models and API",
        "signal_summary": "Google AI Studio is a free browser-based IDE for prototyping with Gemini models — testing prompts, adjusting parameters, and generating API keys for production. It supports multimodal inputs and the full Gemini model family. Free with generous API rate limits.",
        "use_cases": ["code-generation", "research", "productivity", "automation"],
        "price_tier": "free",
        "target_audience": "developers, AI researchers, ML engineers",
        "click_count": 410,
    },
    {
        "name": "GitHub",
        "url": "https://github.com",
        "description": "The world's largest code hosting platform with AI-native features",
        "signal_summary": "GitHub is the world's leading code hosting and collaboration platform, now deeply integrated with AI via Copilot, Copilot Workspace, and AI code review. It hosts over 100 million repositories and is the default home for open-source AI projects. Free for public repos with paid plans for teams.",
        "use_cases": ["code-generation", "productivity", "automation"],
        "price_tier": "freemium",
        "target_audience": "software developers, open-source contributors, DevOps teams",
        "click_count": 900,
    },
    {
        "name": "Docker",
        "url": "https://docker.com",
        "description": "Container platform for building and running AI apps consistently",
        "signal_summary": "Docker is the industry-standard container platform that packages applications and their dependencies into portable containers. It is essential infrastructure for deploying AI models, APIs, and microservices consistently across environments. Free tier for personal use, paid plans for teams.",
        "use_cases": ["automation", "code-generation", "productivity"],
        "price_tier": "freemium",
        "target_audience": "developers, DevOps engineers, ML engineers",
        "click_count": 730,
    },
    # ── Specialised tools ─────────────────────────────────────────────────
    {
        "name": "Hugging Face",
        "url": "https://huggingface.co",
        "description": "The GitHub of AI — models, datasets, and Spaces",
        "signal_summary": "Hugging Face is the central hub for the open-source AI community, hosting 500k+ models, 100k+ datasets, and thousands of interactive Spaces demos. It provides the Transformers library and cloud inference infrastructure. Free for public use, paid Inference Endpoints for production.",
        "use_cases": ["research", "code-generation", "automation", "data-analysis"],
        "price_tier": "freemium",
        "target_audience": "ML researchers, AI developers, data scientists",
        "click_count": 680,
    },
    {
        "name": "Weights & Biases",
        "url": "https://wandb.ai",
        "description": "MLOps platform for experiment tracking, model management, and evaluation",
        "signal_summary": "Weights & Biases (W&B) is the leading MLOps platform for tracking ML experiments, visualising metrics, managing datasets, and evaluating LLMs. It integrates with PyTorch, TensorFlow, Hugging Face, and more. Free for individuals with team and enterprise plans.",
        "use_cases": ["data-analysis", "research", "automation"],
        "price_tier": "freemium",
        "target_audience": "ML engineers, data scientists, AI researchers",
        "click_count": 380,
    },
    {
        "name": "Luma AI",
        "url": "https://lumalabs.ai",
        "description": "AI video generation (Dream Machine) and 3D capture",
        "signal_summary": "Luma AI offers Dream Machine, a fast text-to-video model producing smooth, realistic clips, as well as NeRF-based 3D scene capture from smartphone video. Dream Machine is free to try with paid plans for more generations. Targets creators and 3D artists.",
        "use_cases": ["video-generation", "design", "image-generation"],
        "price_tier": "freemium",
        "target_audience": "filmmakers, 3D artists, content creators",
        "click_count": 370,
    },
    {
        "name": "Pika",
        "url": "https://pika.art",
        "description": "AI video generation and editing with Pika 2.2",
        "signal_summary": "Pika is an AI video generation and editing platform that turns text and images into short video clips with precise motion control. Its Pikaffects feature adds creative physics-based transformations. Freemium with monthly credits.",
        "use_cases": ["video-generation", "design", "content-writing"],
        "price_tier": "freemium",
        "target_audience": "social media creators, designers, marketers",
        "click_count": 340,
    },
    {
        "name": "Framer",
        "url": "https://framer.com",
        "description": "AI-powered website builder for designers",
        "signal_summary": "Framer is a powerful no-code website builder that generates complete, production-ready websites from text descriptions using its AI Mode. It combines professional design control with the speed of AI generation. Freemium with paid plans for custom domains and team collaboration.",
        "use_cases": ["design", "code-generation", "marketing"],
        "price_tier": "freemium",
        "target_audience": "designers, startups, agencies, product teams",
        "click_count": 420,
    },
    {
        "name": "Synthesia",
        "url": "https://synthesia.io",
        "description": "AI video creation with 160+ AI avatars for training and marketing",
        "signal_summary": "Synthesia is an enterprise AI video platform that generates professional videos with realistic AI avatars in 120+ languages from a script. Widely used for employee training, product demos, and multilingual marketing. Subscription-based with business and enterprise plans.",
        "use_cases": ["video-generation", "marketing", "education", "content-writing"],
        "price_tier": "paid",
        "target_audience": "L&D teams, marketers, HR departments, enterprise communications",
        "click_count": 300,
    },
    {
        "name": "Lovable",
        "url": "https://lovable.dev",
        "description": "AI full-stack app builder — go from idea to app in minutes",
        "signal_summary": "Lovable is an AI-powered full-stack application builder that creates React, Supabase-connected web apps from natural language descriptions. It handles frontend, backend, and database setup and deploys automatically. Freemium with credits-based usage.",
        "use_cases": ["code-generation", "productivity", "automation"],
        "price_tier": "freemium",
        "target_audience": "entrepreneurs, non-technical founders, designers",
        "click_count": 360,
    },
    {
        "name": "Webflow",
        "url": "https://webflow.com",
        "description": "Visual web development platform with AI features",
        "signal_summary": "Webflow is a no-code/low-code visual web builder with professional CMS and e-commerce capabilities. Its AI features include component generation and copy writing. Widely used by agencies and marketing teams for production websites. Freemium with paid site plans.",
        "use_cases": ["design", "marketing", "productivity"],
        "price_tier": "freemium",
        "target_audience": "web designers, marketing teams, agencies",
        "click_count": 450,
    },
    {
        "name": "Groq",
        "url": "https://groq.com",
        "description": "Ultra-fast LLM inference via custom LPU hardware",
        "signal_summary": "Groq provides the fastest publicly available LLM inference powered by its custom Language Processing Unit (LPU) chip, achieving 500+ tokens/second on Llama and Mixtral models. Ideal for latency-sensitive applications. Free tier with rate limits and pay-as-you-go API.",
        "use_cases": ["code-generation", "productivity", "automation", "research"],
        "price_tier": "freemium",
        "target_audience": "developers building real-time AI applications",
        "click_count": 390,
    },
    {
        "name": "Hermes (Nous Research)",
        "url": "https://nousresearch.com",
        "description": "Nous Research's high-capability fine-tuned open-source models",
        "signal_summary": "Nous Research's Hermes series are fine-tuned open-source models (based on Llama and Mistral) optimised for instruction following, roleplay, structured output, and agentic tasks. Available free on Hugging Face and via Together AI and OpenRouter. No hosted platform — accessed via third-party providers.",
        "use_cases": ["code-generation", "research", "automation", "writing-assistance"],
        "price_tier": "free",
        "target_audience": "AI developers, researchers, agentic AI builders",
        "click_count": 190,
    },
    {
        "name": "Paperclip AI",
        "url": "https://paperclip.ai",
        "description": "AI knowledge management and document Q&A platform",
        "signal_summary": "Paperclip AI is a knowledge management tool that lets teams upload documents, PDFs, and wikis and query them conversationally. It automatically organises and links related content across your knowledge base. Subscription-based for teams.",
        "use_cases": ["research", "productivity", "data-analysis"],
        "price_tier": "paid",
        "target_audience": "teams, knowledge managers, customer support",
        "click_count": 150,
    },
    {
        "name": "Perplexity Comet",
        "url": "https://perplexity.ai",
        "description": "Perplexity's upcoming AI browser with deep web research capabilities",
        "signal_summary": "Perplexity Comet is an AI-native browser in development by Perplexity AI, designed to assist with agentic web research tasks like booking, comparison shopping, and multi-step information gathering. It represents the next step beyond search into autonomous browsing agents.",
        "use_cases": ["research", "productivity", "automation"],
        "price_tier": "paid",
        "target_audience": "power users, researchers, knowledge workers",
        "click_count": 280,
    },
    {
        "name": "OpenClaw",
        "url": "https://openclaw.ai",
        "description": "AI legal research and contract analysis platform",
        "signal_summary": "OpenClaw is an AI-powered legal research tool that helps lawyers and legal teams analyse contracts, identify risk clauses, and research case law at speed. It reduces review time significantly on standard legal documents. Subscription-based for legal professionals.",
        "use_cases": ["research", "data-analysis", "productivity"],
        "price_tier": "paid",
        "target_audience": "lawyers, legal teams, contract managers",
        "click_count": 110,
    },
    {
        "name": "Together AI",
        "url": "https://together.ai",
        "description": "Cloud platform for training and running open-source AI models fast",
        "signal_summary": "Together AI is a cloud inference and training platform specialising in open-source LLMs, offering fast access to Llama, Mistral, Qwen, and other models via an OpenAI-compatible API. It supports full fine-tuning and model deployment. Pay-as-you-go pricing.",
        "use_cases": ["code-generation", "research", "automation", "data-analysis"],
        "price_tier": "paid",
        "target_audience": "ML engineers, AI startups, researchers",
        "click_count": 270,
    },
    {
        "name": "Phind",
        "url": "https://phind.com",
        "description": "AI search engine optimised for developers and coding questions",
        "signal_summary": "Phind is a developer-focused AI search engine that combines web search with code generation to answer technical questions with cited sources and runnable examples. It uses its own Phind-70B model fine-tuned for coding. Free with a paid Pro tier.",
        "use_cases": ["research", "code-generation", "productivity"],
        "price_tier": "freemium",
        "target_audience": "software developers, engineers",
        "click_count": 330,
    },
    {
        "name": "Sourcegraph Cody",
        "url": "https://sourcegraph.com/cody",
        "description": "AI coding assistant with codebase-wide context",
        "signal_summary": "Cody is Sourcegraph's AI coding assistant that uses the entire codebase — not just open files — as context for code generation, bug fixing, and documentation. It integrates with VS Code, JetBrains, and the web IDE. Free for individuals, paid for teams.",
        "use_cases": ["code-generation", "productivity", "research"],
        "price_tier": "freemium",
        "target_audience": "software developers working on large codebases",
        "click_count": 210,
    },
    {
        "name": "Loom",
        "url": "https://loom.com",
        "description": "AI-powered async video messaging for teams",
        "signal_summary": "Loom is an async video messaging tool that lets you record your screen, camera, and voice and share instantly with a link. AI features auto-generate titles, summaries, chapters, and action items from recordings. Freemium with paid Business plans.",
        "use_cases": ["productivity", "content-writing", "automation"],
        "price_tier": "freemium",
        "target_audience": "remote teams, managers, customer success, sales",
        "click_count": 480,
    },
    {
        "name": "Linear",
        "url": "https://linear.app",
        "description": "Fast, AI-assisted project management for software teams",
        "signal_summary": "Linear is a modern project management tool built for speed and developer workflows, with AI features that auto-fill issue descriptions, suggest labels, and summarise activity. It integrates with GitHub, GitLab, and Slack. Freemium with paid plans for larger teams.",
        "use_cases": ["productivity", "automation"],
        "price_tier": "freemium",
        "target_audience": "software engineering teams, product managers",
        "click_count": 410,
    },
    {
        "name": "Aider",
        "url": "https://aider.chat",
        "description": "Open-source AI pair programmer in your terminal",
        "signal_summary": "Aider is an open-source command-line AI coding tool that works with your existing git repository, using Claude or GPT-4o to make multi-file code changes and auto-commit them. It supports 60+ languages and is fully free to use with your own API key.",
        "use_cases": ["code-generation", "automation", "productivity"],
        "price_tier": "free",
        "target_audience": "developers who prefer terminal workflows",
        "click_count": 280,
    },
    {
        "name": "CrewAI",
        "url": "https://crewai.com",
        "description": "Framework for orchestrating multi-agent AI workflows",
        "signal_summary": "CrewAI is an open-source Python framework for building multi-agent AI systems where specialised agents collaborate on complex tasks. It supports role-based agents, task delegation, and integrates with any LLM. Free to use with an enterprise cloud platform available.",
        "use_cases": ["automation", "research", "code-generation", "productivity"],
        "price_tier": "freemium",
        "target_audience": "AI developers, ML engineers, automation architects",
        "click_count": 310,
    },
    {
        "name": "Codeium",
        "url": "https://codeium.com",
        "description": "Free AI code completion and chat for 70+ languages",
        "signal_summary": "Codeium is a free AI code completion and chat assistant that works inside VS Code, JetBrains, and 40+ other IDEs. It offers fast, context-aware autocomplete and refactoring without a usage cap. Free for individuals, paid for enterprise.",
        "use_cases": ["code-generation", "productivity"],
        "price_tier": "freemium",
        "target_audience": "software developers, students",
        "click_count": 340,
    },
    {
        "name": "Pictory",
        "url": "https://pictory.ai",
        "description": "AI video creation from long-form text and blog posts",
        "signal_summary": "Pictory converts long-form blog posts, scripts, and articles into short branded video clips automatically using AI. It handles scene selection, stock footage, captions, and voice-over. Subscription-based, targeted at content marketers.",
        "use_cases": ["video-generation", "marketing", "content-writing"],
        "price_tier": "paid",
        "target_audience": "content marketers, bloggers, social media managers",
        "click_count": 200,
    },
    {
        "name": "Murf AI",
        "url": "https://murf.ai",
        "description": "AI voice generator with 120+ studio-quality voices",
        "signal_summary": "Murf AI offers a library of 120+ natural-sounding AI voices in 20 languages for creating voiceovers for videos, presentations, and e-learning content. It features a studio interface with pitch, speed, and emphasis controls. Freemium with subscription plans.",
        "use_cases": ["audio-generation", "content-writing", "education"],
        "price_tier": "freemium",
        "target_audience": "content creators, e-learning developers, marketers",
        "click_count": 220,
    },
    {
        "name": "Cohere",
        "url": "https://cohere.com",
        "description": "Enterprise NLP platform — embeddings, generation, and RAG",
        "signal_summary": "Cohere provides enterprise-grade NLP models for text generation, embeddings, classification, and retrieval-augmented generation. Command R+ excels at RAG pipelines and multilingual business tasks. API-first with a free trial tier.",
        "use_cases": ["data-analysis", "research", "automation", "code-generation"],
        "price_tier": "freemium",
        "target_audience": "enterprise developers, ML engineers, data scientists",
        "click_count": 260,
    },
    {
        "name": "AssemblyAI",
        "url": "https://assemblyai.com",
        "description": "Accurate speech-to-text and audio intelligence API",
        "signal_summary": "AssemblyAI provides one of the most accurate speech-to-text APIs with speaker diarisation, sentiment analysis, topic detection, and summarisation built-in. Used by thousands of developers to add audio intelligence to apps. Pay-as-you-go with a free tier.",
        "use_cases": ["audio-generation", "data-analysis", "automation"],
        "price_tier": "freemium",
        "target_audience": "developers building audio-powered applications",
        "click_count": 240,
    },
]


def seed():
    db = SessionLocal()
    added = 0
    skipped = 0

    for data in TOOLS:
        existing = db.query(Tool).filter(Tool.url == data["url"]).first()
        if existing:
            skipped += 1
            continue

        tool = Tool(
            name=data["name"],
            url=data["url"],
            description=data.get("description", ""),
            signal_summary=data["signal_summary"],
            use_cases=json.dumps(data["use_cases"]),
            price_tier=data["price_tier"],
            target_audience=data["target_audience"],
            click_count=data.get("click_count", 0),
            view_count=data.get("click_count", 0),
        )
        db.add(tool)
        added += 1

    db.commit()
    db.close()
    print(f"Done — added {added} tools, skipped {skipped} already existing.")


if __name__ == "__main__":
    seed()
