import { useState, useEffect } from 'react'
import FilterBar from './components/FilterBar.jsx'
import ToolGrid from './components/ToolGrid.jsx'
import AnalyticsDashboard from './components/AnalyticsDashboard.jsx'
import { fetchTools, fetchAnalytics } from './api.js'

export default function App() {
  const [tools, setTools]         = useState([])
  const [analytics, setAnalytics] = useState([])
  const [filters, setFilters]     = useState({})
  const [search, setSearch]       = useState('')
  const [loading, setLoading]     = useState(false)
  const [error, setError]         = useState(null)

  // Debounce search into filters
  useEffect(() => {
    const t = setTimeout(() => {
      setFilters(f => ({ ...f, search: search || undefined }))
    }, 300)
    return () => clearTimeout(t)
  }, [search])

  useEffect(() => {
    setLoading(true)
    setError(null)
    fetchTools(filters)
      .then(setTools)
      .catch(err => setError(err.message))
      .finally(() => setLoading(false))
  }, [filters])

  useEffect(() => {
    fetchAnalytics().then(setAnalytics)
  }, [tools])

  const hasFilter = filters.use_case || filters.price_tier || filters.search

  return (
    <div className="app">
      {/* Hero */}
      <section className="hero">
        <div className="hero-eyebrow">Research Agent</div>
        <h1>Discover the best <span>AI tools</span></h1>
        <p className="hero-sub">
          Signal Summaries generated by AI — tagged by use case and price
        </p>
        <div className="hero-search-wrap">
          <span className="hero-search-icon">⌕</span>
          <input
            className="hero-search"
            type="text"
            placeholder="Search tools by name or description..."
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
        </div>
        <div className="hero-stats">
          <span className="hero-stat"><strong>{tools.length}</strong> tools indexed</span>
          <span className="hero-stat"><strong>13</strong> AI providers supported</span>
        </div>
      </section>

      {/* Sticky category + price pills */}
      <FilterBar filters={filters} onChange={setFilters} />

      {/* Main content */}
      <main className="app-main">
        {error && <div className="error-banner">Failed to load tools: {error}</div>}

        <div className="results-header">
          <p className="results-count">
            {hasFilter
              ? <><strong>{tools.length}</strong> results</>
              : <><strong>{tools.length}</strong> tools</>
            }
          </p>
          {hasFilter && (
            <button
              className="filter-pill"
              style={{ fontSize: 12 }}
              onClick={() => { setFilters({}); setSearch('') }}
            >
              Clear filters ✕
            </button>
          )}
        </div>

        {loading
          ? <div className="loading">Loading tools...</div>
          : <ToolGrid tools={tools} />
        }

        {analytics.length > 0 && (
          <div className="analytics-section">
            <h2>Trending</h2>
            <p>Most visited tools this session</p>
            <AnalyticsDashboard data={analytics} />
          </div>
        )}
      </main>
    </div>
  )
}
